name: CI
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: 🧪 Check
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      node-version: 18.x
      main-branch-name: 'main'
      number-of-agents: 3
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3 --exclude=api --max-warnings=0
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  agents:
    name: ☁️ Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
      node-version: 18.x
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  release:
    name: 📦 Release
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [main]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🟢 Setup NodeJS
        uses: volta-cli/action@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 📦 Execute semantic release
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
